import React from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, Shield, FileText } from 'lucide-react';
import { Logo } from './Logo';

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 20 }}
      className="min-h-screen bg-[#F9FAFB] dark:bg-gray-900 flex flex-col items-center pt-12 pb-24 px-4 transition-colors font-sans"
    >
      <div className="fixed top-8 left-8 z-50">
        <button onClick={onBack} className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors text-gray-500">
            <ArrowLeft size={24} />
        </button>
      </div>

      <div className="w-full max-w-3xl bg-white dark:bg-gray-800 p-8 md:p-12 rounded-3xl shadow-sm border border-gray-100 dark:border-gray-700">
        <div className="flex items-center gap-3 mb-8 border-b border-gray-100 dark:border-gray-700 pb-8">
            <div className="p-2 bg-gray-100 dark:bg-gray-700 rounded-lg text-accent dark:text-white">
                <Logo className="w-8 h-8" />
            </div>
            <div>
                <h1 className="text-3xl font-bold text-accent dark:text-white">Terms of Service</h1>
                <p className="text-gray-500 dark:text-gray-400 text-sm">Last Updated: December 2025</p>
            </div>
        </div>

        <div className="space-y-8 text-gray-600 dark:text-gray-300 leading-relaxed">
            <section>
                <h3 className="text-lg font-bold text-accent dark:text-white mb-3 flex items-center gap-2">
                    <Shield size={18} className="text-primary" /> 1. Acceptance of Terms
                </h3>
                <p className="text-sm">
                    By accessing and using Aura ("the Service"), you agree to be bound by these Terms of Service. 
                    The Service is designed to visualize subjective life events as financial data for entertainment and self-reflection purposes only.
                </p>
            </section>

            <section>
                <h3 className="text-lg font-bold text-accent dark:text-white mb-3 flex items-center gap-2">
                    <FileText size={18} className="text-primary" /> 2. Not Financial or Medical Advice
                </h3>
                <p className="text-sm">
                    Aura uses financial metaphors (e.g., "Liquidation Risk", "Market Crash") to describe personal experiences. 
                    <strong>This is not financial advice, psychological counseling, or medical advice.</strong> 
                    The algorithms used are for visualization only and should not be used to make life-altering decisions.
                </p>
            </section>

            <section>
                <h3 className="text-lg font-bold text-accent dark:text-white mb-3">3. User Data & Privacy</h3>
                <p className="text-sm mb-2">
                    We respect your privacy. Your "Life Events" are stored securely using Supabase encryption protocols.
                </p>
                <ul className="list-disc list-inside text-sm pl-4 space-y-1 opacity-80">
                    <li>We do not sell your personal entries to third parties.</li>
                    <li>You retain full ownership of your data logs.</li>
                    <li>You may delete your account and all associated data at any time via the Settings panel.</li>
                </ul>
            </section>

            <section>
                <h3 className="text-lg font-bold text-accent dark:text-white mb-3">4. Aura Pro Subscription</h3>
                <p className="text-sm">
                    Payments for Aura Pro are processed securely via third-party providers (Helio). 
                    Subscriptions are non-refundable after the billing period has commenced. 
                    Pro features (4K export, infinite history) are revoked immediately upon cancellation.
                </p>
            </section>

            <section>
                <h3 className="text-lg font-bold text-accent dark:text-white mb-3">5. Limitation of Liability</h3>
                <p className="text-sm">
                    Aura is provided "as is". We are not liable for any emotional distress or interpretation of the 
                    data visualizations generated by the platform. Use the "Liquidation Risk" metric with a grain of salt.
                </p>
            </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-100 dark:border-gray-700 text-center">
            <p className="text-xs text-gray-400">
                Contact: support@auraplot.site
            </p>
        </div>
      </div>
    </motion.div>
  );
};